# Generated by Django 4.0.4 on 2022-06-13 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_remove_post_dislikes_alter_image_post_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Плохое слово',
                'verbose_name_plural': 'Плохие слова',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
