# Generated by Django 4.0.4 on 2022-05-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_advuser_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='Прошел ли активацию?'),
        ),
    ]
